#!/bin/bash

#####################################################
#   ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗   #
#   ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║   #
#   ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║   #
#   ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║   #
#   ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║   #
#   ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝   #
#####################################################


BASEDIR=$(dirname "$0")

# Initialization
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom -f --daemon --config "$HOME/.config/picom/picom.conf" &
$HOME/.config/polybar/launch.sh &

# Config
if type "xrandr"; then

  MONITORS=$(xrandr --query | grep " connected" | cut -d" " -f1 | tr '\n' ' ');
  IFS=' ' read -r -a ARR_MONITORS <<< "$MONITORS"

  bspc wm -O $MONITORS
  bspc monitor ${ARR_MONITORS[0]} -d I II III IV V VI

  if [ ${ARR_MONITORS[1]} ]; then
    bspc monitor ${ARR_MONITORS[1]} -d I II
  fi

else
  bspc monitor -d I II III IV V VI
fi

bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.5
bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a ualth border=off



█▀█ █▀▀ █▀█ █▀ █▀█ █▄ █ ▄▀█ █     █▀▀ █▀█ █▄ █ █▀▀ █ █▀▀ █ █ █▀█ ▄▀█ ▀█▀ █ █▀█ █▄ █
█▀▀ ██▄ █▀▄ ▄█ █▄█ █ ▀█ █▀█ █▄▄   █▄▄ █▄█ █ ▀█ █▀  █ █▄█ █▄█ █▀▄ █▀█  █  █ █▄█ █ ▀█

# Keyboard and mouse configurations
xset r rate 250 40
xinput set-prop 'Logitech G502 HERO SE' 'libinput Accel Speed' 1

# Wallpaper
feh --bg-center $BASEDIR/wallpaper.jpg --image-bg "#050505"
