#!/bin/bash

#####################################################
#   ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗   #
#   ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║   #
#   ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║   #
#   ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║   #
#   ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║   #
#   ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝   #
#####################################################


BASEDIR=$(dirname "$0")


#  █▀█ █▀▀ █▀█ █▀ █▀█ █▄ █ ▄▀█ █     █▀▀ █▀█ █▄ █ █▀▀ █ █▀▀
#  █▀▀ ██▄ █▀▄ ▄█ █▄█ █ ▀█ █▀█ █▄▄   █▄▄ █▄█ █ ▀█ █▀  █ █▄█
# ----------------------------------------------------------

# Keyboard and mouse configurations
xset r rate 250 40
xset s 3600
xset -dpms
xinput set-prop 'Logitech G502 HERO SE' 'libinput Accel Speed' 1

# Wallpaper
feh --bg-fill $BASEDIR/wallpaper.jpg --image-bg "#050505"

# Sound device
pactl set-default-sink 'alsa_output.pci-0000_00_1f.3.analog-stereo'

# Initialization
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom -f --daemon --config "$HOME/.config/picom/picom.conf" &

$BASEDIR/startup.sh &
$HOME/.config/polybar/launch.sh &


#  █▄▄ █▀ █▀█ █ █ █ █▀▄▀█   █▀▀ █▀█ █▄ █ █▀▀ █ █▀▀
#  █▄█ ▄█ █▀▀ ▀▄▀▄▀ █ ▀ █   █▄▄ █▄█ █ ▀█ █▀  █ █▄█
# -------------------------------------------------

if type "xrandr"; then

  MONITORS=$(xrandr --query | grep " connected" | grep "+" | cut -d" " -f1 | tr '\n' ' ');
  IFS=' ' read -r -a ARR_MONITORS <<< "$MONITORS"

  bspc wm -O $MONITORS
  bspc monitor ${ARR_MONITORS[0]} -d I II III IV V VI VII VIII

  if [ ${ARR_MONITORS[1]} ]; then
    bspc monitor ${ARR_MONITORS[1]} -d IX X XI XII XIII XIV XV XVI
  fi

else
  bspc monitor -d I II III IV V VI VII VIII
fi

bspc config border_width         2
bspc config window_gap           10



bspc config split_ratio          0.5
bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

wmname LG3D &
bspc rule -a android-studio border=off follow=on
bspc rule -a jetbrains-studio border=off follow=on
bspc rule -a ualth border=off
bspc rule -a Dlancockpit border=off
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

