#!/bin/bash

#####################################################
#   ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗   #
#   ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║   #
#   ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║   #
#   ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║   #
#   ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║   #
#   ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝   #
#####################################################


BASEDIR=$(dirname "$0")

# Initialization
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom -f --daemon --config "$HOME/.config/picom/picom.conf" &
$HOME/.config/polybar/launch.sh &

# Config
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.5
bspc config single_monocle       false
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


###########################
## Default configuration ##
###########################

# Keyboard repeat rate
xset r rate 250 40

# Wallpaper
feh --bg-center $BASEDIR/wallpaper.jpg --image-bg "#050505"
